### ISSUE TITLE
Error on Decider_Admin_Guide_v1.0.0

### ISSUE THREAD

**Issue by GlassHammer1337** [cisagov/decider#17]
Page 9 on admin guide says to sudo mkdir /etc/decider && sudo mv decider.tar.gz /etc/decider/decider.tar.gz

however there is no TAR provided. Figured out that the tar is referencing the files in the git itself.

Recommend changing this to to what it says in the CentOS guide for ease of use

cd /etc sudo git clone https://gitlab.mitre.org/dhs-cisa-cti/decider_tool.git decider

**Comment by damionmounts** [comment]
**Noted!**
Yeah - the guide got a little verbose and botched.
You may realize that `git clone` you pasted references a repo you can't even access externally...

Planning a cut-back set of install instructions that are nicer to maintain (markdown).
But mostly suggesting Docker as the go-to. (Windows & Linux ready, working on a macOS M1 issue)

**Comment by damionmounts** [comment]
Much nicer manual install docs are here by the way:
- https://github.com/cisagov/decider/blob/develop/docs/install/Ubuntu_22.04.2.md
- https://github.com/cisagov/decider/blob/develop/docs/install/CentOS_7.md

Assuming you're not using Docker instead
