### ISSUE TITLE
Ident authentication error

### ISSUE THREAD

**Issue by Hexa60n** [cisagov/decider#19]
'FATAL: Ident authentication failed for user "decider"' error when building initial DB in Fedora local installation.

Fixed this issue by changing authentication method from ident to md5 in /var/lib/pgsql/data/pg_hba.conf

I'm not certain if this is due to a poor installation of postgresql or Fedora being funky.

**Comment by damionmounts** [comment]
Honestly it could have just been a different default. 🤔 
Right now, the Docker image my Mac M1 is pulling defaults to SCRAM-SHA-256 - which isn't yet supported by the app.

I'm really coming to appreciate Docker as a means of normalizing deployment across random systems

**Comment by Hexa60n** [comment]
Yeah, I think you're likely right! Just thought I'd drop it here in case anyone comes across a similar issue.
