### ISSUE TITLE
Decider Docker image installation

### ISSUE THREAD

**Issue by mygithub23** [cisagov/decider#20]
# 🐛 Summary #
I installed decider docker image on 3 environments and one of them failed to run the docker compose. I didn't have any issues installing the decider docker image on Windows and Ubuntu 22. when I tried to install it on redhat 8.7 on AWS EC2 I received an error.

What's wrong? Please be specific.
Error after executing docker compose up command. The error says "Error [decider-web 3/8] RUN pip install --no-cache-dir -- requirement" this happened after COPY ./requirements.txt /requirements.txt step.

**Comment by damionmounts** [comment]
I don't have a RHEL image to test against.
Would you be able to send more lines surrounding that one from the `docker compose up`?

Interested to hear if you've done any debugging as well.

**Comment by mygithub23** [comment]
It looks like I have a permission issues. I took a screenshot about 500k but for some reason I couldn't upload it. I will try again tomorrow.

**Comment by damionmounts** [comment]
I was originally using a folder mount instead of a Docker volume because I figured that might be more convenient.

I changed back to a Docker volume as that should have better compatibility.

No idea if that had any impact for you in particular - but make sure to pull the latest when retrying. 🤞

**Comment by mygithub23** [comment]
The new update is awesome. The decider app now can run on https. Just create a private and public keys and save them in cert folder. Then update .env file by adding---> WEB_HTTPS_ON='yes'

Run docker compose 
Open https://local host:8001


if you want HTTPS instead of HTTP
# - edit .env
#   + WEB_HTTPS_ON='yes'
# - populate cert / key files
#   + /app/utils/certs/decider.key
#   + /app/utils/certs/decider.crt
