### ISSUE TITLE
Issue with Navigator Export

### ISSUE THREAD

**Issue by Jallnutt1** [cisagov/decider#22]
# 🐛 Hello. I am getting an error when I try to upload the navigator export .json to Navigator. 
error I am getting when trying to upload to navigator ![image](https://user-images.githubusercontent.com/30048057/224868449-a7528e92-3dec-4bec-80c4-ca0bf81215ea.png)
Exported .json file from Decider ![image](https://user-images.githubusercontent.com/30048057/224868925-28bda300-128a-45eb-baa8-14b8c1ed2db1.png)
Exported Navigator  .json file from Decider ![image](https://user-images.githubusercontent.com/30048057/224868974-44afdaf5-e923-449b-a978-de8ebe91fa76.png)

**Comment by Jallnutt1** [comment]
Github won't let me attach the actual .json files. Let me know if there is a better way of getting them to you.

**Comment by damionmounts** [comment]
Current priority is ensuring that the manual install instructions (non-Docker) are corrected..

**But**, this may be as simple as tweaking the navigator/layer version markers in the exported JSON.
Would need to check if there are any differences in how the data is structured.

![nav-export-versioning](https://user-images.githubusercontent.com/31434109/224906474-352e4354-420c-4fae-a0ca-299b58640092.png)

**Comment by Jallnutt1** [comment]
Cool, thanks for such a quick reply. I will give tweaking the file a try. 

Side note, updating the manual for non-docker install would be great. Thanks for working on that.

**Comment by damionmounts** [comment]
- Let me know how tweaking the file goes.
  - Could even knock this out today.
- Sure deal! Looking to have all the manual-install docs updated as this week ends out.
  - Thinking about migrating from .pdf to .md so that doc-change-PRs are actually a thing
  - / Viewing docs in your IDE is smooth

**Comment by damionmounts** [comment]
Tweak was a little different - but basically a version bump.
Closing as it is merged in: https://github.com/cisagov/decider/pull/26

**Comment by damionmounts** [comment]
@Jallnutt1 

Closed issue - but, much nicer Ubuntu and CentOS docs have been added:
- https://github.com/cisagov/decider/blob/develop/docs/install/Ubuntu_22.04.2.md
- https://github.com/cisagov/decider/blob/develop/docs/install/CentOS_7.md
