### ISSUE TITLE
issue with the /opt/decider/entrypoint.sh file

### ISSUE THREAD

**Issue by samuellopeztre** [cisagov/decider#36]
# 🐛 Summary #

The  /opt/decider/entrypoint.sh is showing Syntax error: "fi" unexpected (expecting "then"). I have observerved this file was updated yesterday

## To reproduce ##

Just execute
cp .env.docker .env
docker compose up

## Expected behavior ##

The web server running

Thanks in advance

**Comment by damionmounts** [comment]
Hello hello,

I recently removed dos2unix from web (which originally fixed an issue running entrypoint.sh on Windows hosts with Decider on Docker).

I had reconfigured my git-on-windows to use LF line-endings on checkout.

Please let me know if you're on Windows, and if re-cloning with line-endings changed fixes it for you

**Comment by samuellopeztre** [comment]
Thanks for your quick reply
Yes, I am using windows but getting the same error if re-cloning with line-ending
Any other idea?
Regards

**Comment by damionmounts** [comment]
### I think you're running into cache issues
Docker caches build layers in-order to speed-up subsequent builds.
This causes pain when changed files don't seem to effect anything.

#### Line-ending Preface

##### Global Config
```bash
git config --global core.eol=lf
git config --global core.autocrlf=false
```

##### Per-Clone Options
```bash
git clone -c core.eol=lf -c core.autocrlf=false https://github.com/cisagov/decider.git
```

#### ⭐ Solution

Remove Decider's containers and volumes
```bash
docker compose down --volumes
```

Build Again - But don't use the cached layers containing the bad line-endings
```bash
docker compose build --no-cache
```

Launch
```bash
docker compose up
```

**Success - entrypoint.sh runs**
```
decider-db-1   | 2023-04-11 12:48:59.817 UTC [1] LOG:  database system is ready to accept connections
decider-web-1  | Overwriting / creating user.json file with admin (ADMIN_EMAIL, ADMIN_PASS)
```

---

Please let me know if this works for you!

**Comment by damionmounts** [comment]
I am seeing about including a `.gitattributes` file in the repo - this should automatically make clone use LF for Windows users, regardless of Git settings.

**Comment by samuellopeztre** [comment]
Hi
You were totally right, i have been able to figure this issue out
thanks for your support

**Comment by damionmounts** [comment]
You're welcome!
Glad I could help out.
