### ISSUE TITLE
entrypoint.sh error

### ISSUE THREAD

**Issue by kainewill** [cisagov/decider#37]
# 🐛 Summary #

What's wrong? Please be specific.

Error when running the command "docker compose up"
it fail when it gets to the web build session.

: not found-1  | /opt/decider/entrypoint.sh: 2:
decider-web-1  | /opt/decider/entrypoint.sh: 83: Syntax error: end of file unexpected (expecting "then")
decider-web-1 exited with code 2

## Any helpful log output or screenshots ##

Paste the results here:

decider-db-1   | 2023-04-13 00:58:08.620 UTC [38] LOG:  shutting down
decider-db-1   | 2023-04-13 00:58:08.664 UTC [36] LOG:  database system is shut down
decider-db-1   |  done
decider-db-1   | server stopped
decider-db-1   |
decider-db-1   | PostgreSQL init process complete; ready for start up.
decider-db-1   |
decider-db-1   | 2023-04-13 00:58:08.746 UTC [1] LOG:  starting PostgreSQL 14.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
decider-db-1   | 2023-04-13 00:58:08.749 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
decider-db-1   | 2023-04-13 00:58:08.752 UTC [1] LOG:  listening on IPv6 address "::", port 5432
decider-db-1   | 2023-04-13 00:58:08.762 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
decider-db-1   | 2023-04-13 00:58:08.776 UTC [53] LOG:  database system was shut down at 2023-04-13 00:58:08 UTC
decider-db-1   | 2023-04-13 00:58:08.783 UTC [1] LOG:  database system is ready to accept connections
: not found-1  | /opt/decider/entrypoint.sh: 2:
decider-web-1  | /opt/decider/entrypoint.sh: 83: Syntax error: end of file unexpected (expecting "then")
decider-web-1 exited with code 2

**Comment by damionmounts** [comment]
## 💻 Solution Below

I added dos2unix back which will fix the CRLF line-endings that Windows git checks out.
That of which are not compatible with bash, which expects LF endings.

Was originally going to pursue a .gitattributes solution - but that can have side-effects.
This is self contained in the container

```bash
git pull
docker compose build web --no-cache
docker compose up
```

**Please let me know if this solves it for you!**

**Comment by kainewill** [comment]
> ## 💻 Solution Below
> I added dos2unix back which will fix the CRLF line-endings that Windows git checks out. That of which are not compatible with bash, which expects LF endings.
> 
> Was originally going to pursue a .gitattributes solution - but that can have side-effects. This is self contained in the container
> 
> ```shell
> git pull
> docker compose build web --no-cache
> docker compose up
> ```
> 
> **Please let me know if this solves it for you!**

It solved the error message but for some reason the page is no longer loading

**Comment by damionmounts** [comment]
> It solved the error message but for some reason the page is no longer loading

Oh no.

### Ideas:
- Double-check `WEB_IP`, `WEB_PORT`, and `WEB_HTTPS_ON` settings in .env
- Navigate to the root page of the web-app as a baseline test of functionality
- Check the web container logs / post here if needed

**Comment by damionmounts** [comment]
## :brain: Another Thought

Even though you probably selected HTTP**S**, see if it's actually hosting on HTTP.

I ran into this issue in another place - and needed to add `WEB_HTTPS_ON: ${WEB_HTTPS_ON}` under the environment for the web service inside my docker compose file

**Comment by kainewill** [comment]
> ## 🧠 Another Thought
> Even though you probably selected HTTP**S**, see if it's actually hosting on HTTP.
> 
> I ran into this issue in another place - and needed to add `WEB_HTTPS_ON: ${WEB_HTTPS_ON}` under the environment for the web service inside my docker compose file

@damionmounts thank you. The issue was resolved and the CentOS 7 installation was also successful. Appreciate your hard work on this application.

**Comment by damionmounts** [comment]
I'm glad that I could help you out here!
And thank you - just doing what I can!
