### ISSUE TITLE
CISA Decider DB error

### ISSUE THREAD

**Issue by Sparxicus** [cisagov/decider#84]
# 🐛 Summary #

Error is created when using Docker to clone git from CISA.gov Installation page in Github.  

Setup:
Docker Desktop in Windows 11 that uses Ubuntu distro combined with WSL.

I had no problems with Decider Webapp; only with Decider db/Postgres.
![Error_Screenshot](https://github.com/cisagov/decider/assets/13308430/4638631a-00b4-4709-b9bb-5257ac4d84a4)

ERROR:  
Cannot start Docker Compose application. Reason: compose [start] exit status 1. Container decider-db Starting Container decider-db Started Container decider-db Waiting Container decider-db Error dependency failed to start: container decider-db is unhealthy

## To reproduce ##
On Docker Desktop, using Windows terminal/Ubuntu, copy code and enter into terminal in Ubuntu and it should produce the following error.

**Comment by damionmounts** [comment]
Hello - sorry you're running into any issues!

Did you make sure to edit `.env` after copying `.env.docker` to it?

**Comment by Sparxicus** [comment]
Hey Damion,
I did not and not sure how to do it.  I looked in the guidance doc and under Installation.  It's local on my machine.

Is there any guidance you can provide on how to define below?

cp .env.docker .env
# edit .env - define DB_ADMIN_PASS, DB_KIOSK_PASS, CART_ENC_KEY, APP_ADMIN_PASS

**Comment by damionmounts** [comment]
Hello again,

Your Ubuntu/WSL machine should have nano (a terminal-based text editor) available.

Type `nano .env` in your console and nano should open the .env file for editing.

Make sure to place a password on any of the lines ending in `=`.
Example:
<img width="456" alt="image" src="https://github.com/cisagov/decider/assets/31434109/50279ad6-00f5-4f2f-aeda-2d83cfcdf181">

Once you've done that - hit **Ctrl-X** to exit.
Press **Y** and then **Enter** to confirm saving on exit.

Then retry `sudo docker compose up` to see if things are working.
Let me know how it goes!

**Comment by Sparxicus** [comment]
Hey there,

Thanks for instructions above, I tried to follow along.  I use Ubuntu terminal to connect via WSL to Docker Desktop. Typing in nano .env does NOT open the .env file for editing.  It opens the terminal and I can type in anything.


![Screenshot 2024-04-09 123627](https://github.com/cisagov/decider/assets/13308430/2b445808-e050-481e-8d88-2a73d7835f31)

**Comment by damionmounts** [comment]
What directory are you in? (`pwd` will give the full path)
Make sure that you're inside the Decider repo directory - and that `.env` exists by running `ls -la` and seeing it in the file listing.
If you need - re-copy `.env.docker` to `.env`.
Or just copy this into nano and save:
```
# Docker Deployment



# DATABASE ---------------------------------------------------------------------

# db to create and use
DB_DATABASE=decider

# admin (full-access, used in db scripts / normal modes)
DB_ADMIN_NAME=decideradmin
DB_ADMIN_PASS=samplePassword123

# kiosk (limited read-only, used in kiosk mode)
DB_KIOSK_NAME=deciderkiosk
DB_KIOSK_PASS=samplePassword123

# cart encryption key
CART_ENC_KEY=samplePassword123



# WEB-APP ----------------------------------------------------------------------

# app admin login
APP_ADMIN_EMAIL=admin@admin.com
APP_ADMIN_PASS=samplePassword123

# connect to this db (uses DB_DATABASE) (do not edit if using Docker)
DB_HOSTNAME=db
DB_PORT=5432

# only for Docker deployment - not manual (host on http(s)://WEB_IP:WEB_PORT/, WEB_HTTPS_ON='yes' for HTTPS)
WEB_IP=127.0.0.1
WEB_PORT=8001
WEB_HTTPS_ON=''
```

**Comment by Sparxicus** [comment]
Appreciate your patience...getting closer.  How do I pass changes/updates made in Visual Studio to .env in Docker?

![Screenshot 2024-04-09 144208](https://github.com/cisagov/decider/assets/13308430/accad1e6-ca46-4f59-82c8-c4cc63ff0ccc)

**Comment by damionmounts** [comment]
Of course - glad to help!

**_Fair warning_** - I see that you cloned a copy of Decider into an existing copy of Decider. You should likely remove the inner copy. That outer copy is probably the original one used by Docker Desktop.

1. From the current screenshot / view - you should copy what's in the `.env` on screen - and paste it into the `.env` in the root / outermost folder.

1. Then delete the decider folder that is the 4th item in the file browser - keeping the root folder/copy of course.

1. Then you should be able to launch it within Docker Desktop.

Don't ever feel opposed to starting fresh - it's a great way to ensure everything is as it should be!

**Comment by damionmounts** [comment]
\^ \*doesn't have to be within Docker Desktop - `sudo docker compose up` should work just fine in the terminal

**Comment by Sparxicus** [comment]
Boom....I got it to work.  Thanks for giving me a tutorial on Docker and Linux.  I owe you.  For updates, are they pushed out or do I need to pull them on a regular cadence?

**Comment by damionmounts** [comment]
**Woot!**

Pull based - `git pull` and then `sudo docker compose up --build` every once in a while should keep you up-to-date.

There should only really be polish or ATT&CK data updates.
