### ISSUE TITLE
nginx reverse proxy config advice

### ISSUE THREAD

**Issue by 0kn0t0K** [cisagov/decider#87]
Using NGINX resverse proxy in front of decider and getting  502 Bad Gateway (nginx/1.25.4)
There seems to be an issue with redirect to decider.local.lan/question/v14.1

Nginx Error log: 
` [error] 29#29: *1 upstream sent "Content-Length" and "Transfer-Encoding" headers at the same time while reading response header from upstream, client: 172.28.0.66, server: decider.local.lan, request: "GET /question/v14.1 HTTP/1.1", upstream: "http://192.168.128.3:5000/question/v14.1", host: "decider.local.lan"`

Running Decider Docker

I can access the logo image at https://decider.local.lan/static/cisa-logo.svg, so site is accessible, just can't get to homepage

hostnames are included in my /etc/hosts/

nginx  location config:
	

```
location / {
	    resolver 127.0.0.10 valid=5s;
	    set $upstream_endpoint http://decider-web:5000;
	    include  /etc/nginx/mime.types;
	    proxy_pass $upstream_endpoint;
	    proxy_redirect     off;
	    proxy_set_header   Host $host;
	    proxy_set_header   X-Real-IP $remote_addr;
	    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header   X-Forwarded-Host $server_name;
	}


```

**Comment by damionmounts** [comment]
Hello!

Please let me know if modifying the uwsgi.ini configs - as documented in https://github.com/cisagov/decider/issues/78 - seems to fix the issue.

And thank you for including your config + error log - that'll help steer fixing it properly instead of just lopping the config as a fast check.

**Comment by 0kn0t0K** [comment]
Yes, this fix resolved my issue.

Thank you for your help and the fast response.  Much appreciated

**Comment by damionmounts** [comment]
Glad that worked for you!

I'll need to adjust the config later
