### ISSUE TITLE
"User Guide" refers to non-existent PDF file

### ISSUE THREAD

**Issue by AlLongley** [cisagov/decider#88]
# 🐛 Summary #

The following section on the repository's main Readme page references the following section

> 
> 📖 User Guide
> [Over Here](https://github.com/cisagov/decider/blob/develop/docs/user_guide_3_0_0/user-guide-3-0-0.pdf)
> 

## To reproduce ##

Follow this link to relevant section

https://github.com/cisagov/decider?tab=readme-ov-file#book-user-guide

## Expected behavior ##

A linked PDF should render within the repository, or any replacement document such as **user-guide.md** 

"https://github.com/cisagov/decider/blob/develop/docs/user_guide_3_0_0/user-guide.md"

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by damionmounts** [comment]
**Updated!**

Thank you for the issue :)
