### ISSUE TITLE
Issue during DB init (full technique search)

### ISSUE THREAD

**Issue by mhansonibm** [cisagov/decider#9]
___________Creating index for full Technique search
Failed to add ATT&CK/Tree content for version v12.0 at 1.0s into build - due to:
(psycopg2.errors.UndefinedFunction) function imm_unaccent(text) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: DROP INDEX IF EXISTS tech_ts_index;
    ALTER TABLE technique DROP COLUMN IF EXISTS tech_ts;

    ALTER TABLE technique ADD COLUMN tech_ts tsvector
        GENERATED ALWAYS AS
            (setweight(to_tsvector('english_nostop',
            imm_unaccent(technique.full_tech_name)), 'B') ||
            setweight(to_tsvector('english_nostop',
            regexp_replace(technique.tech_id ||
            ' ' || substr(technique.tech_id, 2), '[^a-z0-9 ]+', ' ', 'gi')), 'A') ||
            setweight(to_tsvector('english_nostop',
            regexp_replace(regexp_replace(regexp_replace(regexp_replace(imm_unaccent(technique.tech_description),
            '<\/?(sup|a|code)[^>]*>', '', 'gi'), '\[[0-9]{1,2}\]', '', 'gi'),
            '\[([^\]]+)\]\([^\)]+\)', '\1', 'gi'), '[^a-z0-9 ]', ' ', 'gi')), 'D')) STORED;
    CREATE INDEX tech_ts_index ON technique USING gist(tech_ts);]

**Comment by damionmounts** [comment]
Hello @mhansonibm!
The following SQL should help you out.

This lives inside of initial_setup.py as the variable `init_sql_template` (line 13) - and gets populated to form init.sql which initializes the database before any builds can occur.

This will give you the missing `imm_unaccent()` function. Please make sure to populate the template / cull it down to what you actually need though.

Please let me know if this solves it for you!

```sql
-- Flask Connection / Only User
CREATE USER {db_user_name} WITH LOGIN PASSWORD '{db_user_pass}';
CREATE DATABASE decider;
\\c decider;
GRANT ALL PRIVILEGES ON DATABASE decider to {db_user_name};

-- Used for top-right Technique search - WORD_SIMILARITY()
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- fake mutable unaccent function for full search
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;
DROP FUNCTION IF EXISTS imm_unaccent;
CREATE FUNCTION imm_unaccent(text) RETURNS text AS $$
BEGIN
    RETURN unaccent($1);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Dictionary for Full Search, doesn't remove stop words "a", "the", ..
DROP TEXT SEARCH CONFIGURATION IF EXISTS english_nostop;
DROP TEXT SEARCH DICTIONARY IF EXISTS english_stem_nostop;
CREATE TEXT SEARCH DICTIONARY english_stem_nostop (template = snowball, language = english);
CREATE TEXT SEARCH CONFIGURATION english_nostop (copy = english);
ALTER TEXT SEARCH CONFIGURATION english_nostop ALTER MAPPING REPLACE english_stem WITH english_stem_nostop;
```

**Comment by alorello** [comment]
I had the same problem, and running the commands init.sql as is didn't fix it, but here is why: 
The database in this init file is named `decider`, but the various Config classes in `app/conf.py` use other names, like "production_5000_all_mii". In my case, I changed the database name in DefaultConfig to `decider` and then ran the sequence of commands in init.sql file, followed by `python -m app.utils.db.actions.full_build` 

This fixed the issue for me.

**Comment by alorello** [comment]
The above might seem obvious, but I'd hazard that @mhansonibm did what I had done, which is to create and initialize a db called "production_5000_all_mii" after running the init.sql file as is (with db `decider`). The reason we get these errors is that postgresql functions and extensions are not globally scoped, they are scoped to the database the are created in.

**Comment by damionmounts** [comment]
Apologies on that!
The config file app/conf.py needed to be corrected to have the defaults `host="localhost"` and `database="decider"`.
Missed that in initial file delivery.

That's merged into develop now

**Comment by damionmounts** [comment]
It seems like everything is solved here -

_**But was there any other support needed on this issue before I close it?**_

Thanks 😄

**Comment by alorello** [comment]
I just built this in a docker container for a coworker using the latest develop and didn't run into this issue, so I'd say its resolved!

**Comment by mhansonibm** [comment]
Apologies, yes, I believe we're good to go now.

**Comment by damionmounts** [comment]
😎 👍 
Glad to hear it.
Closing-out.
Have a good weekend!
