### ISSUE TITLE
Adding the JSON files for MITRE ATT&CK Framework Version 15.0

### ISSUE THREAD

**Issue by mfacemire** [cisagov/decider#91]
For planning purposes, I was wondering your planned completion date for the addition and modification of the MITRE ATT&CK Framework Version 15.0 JSON files to the Decider repository.

**Comment by damionmounts** [comment]
Thanks for asking!

Currently, the planned window is **this Friday - Monday**.
I'll close this thread with a notice once it's finished.

**Comment by damionmounts** [comment]
Good morning, **it is done**: https://github.com/cisagov/decider/pull/92 !

Updating should be as simple as:
```sh
git pull
cp -r default_config/. config/
sudo docker compose up
```
