### ISSUE TITLE
Connection Refused via Web, password authentication failed via CLI

### ISSUE THREAD

**Issue by jkonderla-PEP** [cisagov/decider#97]
# 🐛 Summary #

Unable to load site after fresh docker install, received the error 'refused to connect' in the browser. When using the "docker compose up" command I saw the error of "connection to server at "db" (172.23.0.2), port 5432 failed: FATAL:  password authentication failed for user "decideradmin""
## To reproduce ##

1. Defined the default credentials in the file while following the suggested steps on the main decider project page.

2. Brought the containers up using "sudo docker compose up".
3. Attempted to access via the web portal (http://10.1.10.111:8001).

## Expected behavior ##

The website to load properly on the pre-defined port.

## Any helpful log output or screenshots ##

The variables in .env:
`# admin (full-access, used in db scripts / normal modes)
DB_ADMIN_NAME=decideradmin
DB_ADMIN_PASS=D3c1d3rAdm1n

# kiosk (limited read-only, used in kiosk mode)
DB_KIOSK_NAME=deciderkiosk
DB_KIOSK_PASS=D3c1d3rK10sk

# cart encryption key
CART_ENC_KEY=a9OGQZnxCDo6RDx4RGGoF6eaup2I6Kvs`

Paste the results here:

```console
decider-web  | ___________Removing all tables from DB
decider-web  | Failed to recreate tables at 0.0s into build - due to:
decider-web  | (psycopg2.OperationalError) connection to server at "db" (172.23.0.2), port 5432 failed: FATAL:  password authentication failed for user "decideradmin"
decider-web  |
decider-web  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

Information provided on the sqlalche.me page was not helpful at all. Tried completely removing and purging the docker containers AND files from host, re-added them using the same instructions on the main project page with same result.

**Comment by damionmounts** [comment]
Hello there, sorry you're running into this - but I think I know what's wrong.

That error tells us that the user `decideradmin` exists, but that we have the wrong password for it.

You likely have an old `decider_db_data` volume from when the database was created under a different password.

### Try running
```bash
sudo docker compose down -v
sudo docker compose up
```

`-v` will remove the volume and cause a new DB to be built when bringing it back up

**Comment by jkonderla-PEP** [comment]
That did it! Thanks @damionmounts !
